export const SET_USERS = 'SET_USERS';
export const SET_REASONS = 'SET_REASONS';
export const SET_SELECTED_EMPLOYEE = 'SET_SELECTED_EMPLOYEE';
export const SET_SELECTED_REASON = 'SET_SELECTED_REASON';
export const SET_VISITOR = 'SET_VISITOR';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const CLAER_EXPIREDMESSAGES = 'CLAER_EXPIREDMESSAGES';
export const CLAER_READMESSAGES = 'CLAER_READMESSAGES';

